# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapsed', models.BooleanField(default=True)),
                ('text', models.CharField(blank=True, max_length=999, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MemTree.Item')),
            ],
        ),
    ]
