# Generated by Django 4.0.6 on 2024-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemTree', '0002_auto_20220515_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
