# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dayRate', models.FloatField()),
                ('nightRate', models.FloatField()),
                ('dayE1', models.IntegerField()),
                ('dayConsumption', models.IntegerField()),
                ('dayCost', models.FloatField()),
                ('nightE2', models.IntegerField()),
                ('nightConsumption', models.IntegerField()),
                ('nightCost', models.FloatField()),
                ('totalCost', models.FloatField()),
                ('neighbors', models.IntegerField()),
                ('neighborsCost', models.FloatField()),
                ('us', models.IntegerField()),
                ('usCost', models.FloatField()),
                ('neCost', models.FloatField()),
            ],
        ),
    ]
