# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='dayConsumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='dayCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='dayE1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='dayRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='neCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='neighbors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='neighborsCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='nightConsumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='nightCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='nightE2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='nightRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='totalCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrodata',
            name='usCost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
