# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorynych', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintreedatabase',
            name='collapsed',
            field=models.BooleanField(default=True),
        ),
    ]
