# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('dayRate', models.FloatField(blank=True, null=True)),
                ('nightRate', models.FloatField(blank=True, null=True)),
                ('dayE1', models.IntegerField(blank=True, null=True)),
                ('dayConsumption', models.IntegerField(blank=True, null=True)),
                ('dayCost', models.FloatField(blank=True, null=True)),
                ('nightE2', models.IntegerField(blank=True, null=True)),
                ('nightConsumption', models.IntegerField(blank=True, null=True)),
                ('nightCost', models.FloatField(blank=True, null=True)),
                ('totalCost', models.FloatField(blank=True, null=True)),
                ('neighbors', models.IntegerField(blank=True, null=True)),
                ('neighborsCost', models.FloatField(blank=True, null=True)),
                ('us', models.IntegerField(blank=True, null=True)),
                ('usCost', models.FloatField(blank=True, null=True)),
                ('neCost', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
